# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-xenial:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: repo

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cd $GITHUB_WORKSPACE/repo/
          pwd
          apt-get update
          apt-get install devscripts equivs build-essential:amd64 debhelper dh-python dh-systemd python-setuptools python-all -y
          mk-build-deps -i || true
          dpkg-buildpackage -us -uc -b
          ls -la
          ls -la ../          
          
      - name: Upload deb
        uses: actions/upload-artifact@v2.2.3
        with: 
          name: mdns-publisher-xenial
          path: ${{ github.workspace }}/*.deb

  build-bionic:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: repo

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cd $GITHUB_WORKSPACE/repo/
          pwd
          apt-get update
          apt-get install devscripts equivs build-essential:amd64 debhelper dh-python dh-systemd python-setuptools python-all -y
          mk-build-deps -i || true
          dpkg-buildpackage -us -uc -b
          ls -la
          ls -la ../          

      - name: Upload deb
        uses: actions/upload-artifact@v2.2.3
        with: 
          name: mdns-publisher-bionic
          path: ${{ github.workspace }}/*.deb

